module "node1" {
  source = "../../modules/aws/ec2/launch-configurations/sidechain-node"

  app_name            = "${var.app_name}"
  environment_name    = "${var.environment_name}"
  key_name            = "${var.key_name}"
  volume_size_gb      = "${var.instance_disk_size}"
  vpc_id              = "${var.vpc_id}"
  ami                 = "${var.ami}"
  subnet_ids          = "${var.subnet_ids}"
  availability_zones  = "${var.aws_availability_zones}"
  desired_capacity    = "${var.nodes_count}"
  min_size            = "${var.nodes_count}"
  max_size            = "${var.nodes_count}"

  ethereum_confirmation_block   = "${var.ethereum_confirmation_block}"
  ethereum_url                  = "${var.ethereum_url}"
  etherscan_api_key             = "${var.etherscan_api_key}"
  etherscan_url                 = "${var.etherscan_url}"
  props_token_contract_address  = "${var.props_token_contract_address}"
  props_token_deployed_block    = "${var.props_token_deployed_block}"
  sawtooth_pk                   = "${var.sawtooth_pk}"
  validator_url                 = "${var.validator_url}"
  network_private_key           = "${var.network_private_key}"
  network_public_key            = "${var.network_public_key}"
}
